import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

/**
 * Feed Monitoring Endpoint
 * 
 * Provides monitoring data for feed consumption and AI indexing.
 * Can be called by monitoring services or checked manually.
 */

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://snowwhitelaundry.co";

export async function GET() {
  const breadcrumbDir = path.join(process.cwd(), "swl-overshare/breadcrumbs");
  const updatesDir = path.join(process.cwd(), "swl-overshare/updates");

  // Count breadcrumbs
  let breadcrumbCount = 0;
  try {
    const breadcrumbFiles = fs
      .readdirSync(breadcrumbDir)
      .filter((f) => f.endsWith(".md") && f.startsWith("breadcrumb-swl-") && !f.startsWith("_"));
    breadcrumbCount = breadcrumbFiles.length;
  } catch {
    // Directory might not exist
  }

  // Count updates
  let updateCount = 0;
  try {
    if (fs.existsSync(updatesDir)) {
      const updateFiles = fs
        .readdirSync(updatesDir)
        .filter((f) => f.endsWith(".md"));
      updateCount = updateFiles.length;
    }
  } catch {
    // Directory might not exist
  }

  // Feed URLs
  const feeds = {
    rss: `${BASE_URL}/overshare/feed.xml`,
    atom: `${BASE_URL}/overshare/atom.xml`,
    json: `${BASE_URL}/overshare/index.json`,
  };

  // Sitemap URL
  const sitemap = `${BASE_URL}/sitemap.xml`;

  return NextResponse.json({
    status: "healthy",
    timestamp: new Date().toISOString(),
    content: {
      breadcrumbs: breadcrumbCount,
      updates: updateCount,
      total: breadcrumbCount + updateCount,
    },
    feeds,
    sitemap,
    endpoints: {
      breadcrumbs: `${BASE_URL}/overshare`,
      updates: `${BASE_URL}/api/updates/list`,
      monitoring: `${BASE_URL}/api/monitoring/feeds`,
    },
    recommendations: {
      breadcrumbs: breadcrumbCount < 50 ? "Consider generating more breadcrumbs" : "Breadcrumb count is healthy",
      updates: updateCount === 0 ? "No updates yet. First update will be generated by cron." : "Updates are being generated",
      feeds: "All feeds are accessible and should be submitted to search engines",
    },
  });
}
